In [1]:
import pandas as pd
import os
import math

In [2]:
users = pd.read_csv("./data/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["A1", "A2", "A3", "A4", "A5", "A6", "A7"]

# path

In [3]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_id in users["uuid"]:

        path_length = 0
        df_path = task_dict[user_id]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,path_A3,path_A4,path_A5,path_A6,path_A7
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,1630.555929,2233.008738,2170.048275,1972.911950,1921.064231
1,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,4557.869391,3359.160380,1967.367374,1385.118367,1505.599067
2,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,2804.593382,1752.220885,2275.562554,2397.306043,1766.503075
3,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,1722.585509,1195.747036,1327.765554,1609.162690,1795.772668
4,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,2578.500033,1338.062532,2692.813557,1933.835209,2315.049794
5,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,2213.886556,3205.307108,1533.996385,2106.101745,1747.298173
6,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,2031.827472,2116.215184,1429.805509,1722.544772,1257.335812
7,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,1347.656057,1346.142714,1532.009429,1813.993850,1481.313211
8,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,2836.668418,2033.994637,2622.563570,2532.719558,2753.232395
9,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,1919.894898,1282.122331,1685.211628,1593.377909,1329.119580
10,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,1860.191943,1445.918542,2118.409034,1341.397471,1492.642654
11,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,2113.841198,1116.665460,1562.121425,1773.880057,1758.528557

# time

In [9]:
for task in tasks:
    
    task_times = []

    for user in users["uuid"]:
        df = pd.read_csv("data/tracking_files/" + user + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"])

    users["time_" + task] = task_times

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,path_A3,...,path_A5,path_A6,path_A7,time_A1,time_A2,time_A3,time_A4,time_A5,time_A6,time_A7
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,1630.555929,...,2170.048275,1972.911950,1921.064231,4394,4354,4272,4863,4698,4369,3609
1,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,4557.869391,...,1967.367374,1385.118367,1505.599067,3945,5840,6694,3107,3389,2188,2102
2,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,2804.593382,...,2275.562554,2397.306043,1766.503075,7281,4908,3582,3909,3666,4460,4283
3,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,1722.585509,...,1327.765554,1609.162690,1795.772668,3789,3532,3771,3538,3185,3467,4232
4,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,2578.500033,...,2692.813557,1933.835209,2315.049794,6669,12182,9164,11400,9902,6768,15800
5,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,2213.886556,...,1533.996385,2106.101745,1747.298173,6783,4655,5391,7281,4424,5456,4447
6,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,2031.827472,...,1429.805509,1722.544772,1257.335812,7818,5376,7072,6122,6986,8179,4742
7,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,1347.656057,...,1532.009429,1813.993850,1481.313211,4358,4674,6541,5064,4560,4091,7002
8,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,2836.668418,...,2622.563570,2532.719558,2753.232395,3496,4592,4818,4896,4049,3601,5248
9,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,1919.894898,...,1685.211628,1593.377909,1329.119580,3569,4476,4104,5596,4513,4304,4199
10,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,1860.191943,...,2118.409034,1341.397471,1492.642654,6406,3906,4411,3732,3552,4110,4589
11,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,2113.841198,...,1562.121425,1773.880057,1758.528557,5688,5141,7125,5682,5210,6044,4272

# describe

In [10]:
users.describe()

,age,sorting_option,num_of_files,path_A1,path_A2,path_A3,path_A4,path_A5,path_A6,path_A7,time_A1,time_A2,time_A3,time_A4,time_A5,time_A6,time_A7
count,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,38.666667,1.750000,23.0,2411.222806,1606.794324,2301.505899,1868.713796,1909.806191,1848.529135,1760.288268,5349.666667,5303.000000,5578.750000,5432.500000,4844.500000,4753.083333,5377.083333
std,17.195842,0.866025,0.0,533.785852,772.070655,845.230292,759.111109,466.507185,366.225493,423.643543,1588.608215,2252.074882,1725.727627,2226.905497,1889.003898,1618.228968,3466.112348
min,23.000000,1.000000,23.0,1798.996408,962.908791,1347.656057,1116.665460,1327.765554,1341.397471,1257.335812,3496.000000,3532.000000,3582.000000,3107.000000,3185.000000,2188.000000,2102.000000
25%,25.000000,1.000000,23.0,1952.638256,1079.776060,1825.790334,1324.077482,1533.499646,1605.216494,1489.810293,3906.000000,4445.500000,4230.000000,3864.750000,3637.500000,3968.500000,4223.750000
50%,25.500000,1.500000,23.0,2196.798190,1381.002302,2072.834335,1599.069714,1826.289501,1793.936953,1752.913365,5041.000000,4664.500000,5104.500000,4980.000000,4468.500000,4336.500000,4365.000000
75%,56.000000,2.250000,23.0,2949.507532,1660.808322,2635.023370,2145.413573,2196.426845,2006.209399,1827.095559,6697.500000,5199.750000,6788.500000,5792.000000,4826.000000,5603.000000,4868.500000
max,61.000000,3.000000,23.0,3202.784211,3433.884540,4557.869391,3359.160380,2692.813557,2532.719558,2753.232395,7818.000000,12182.000000,9164.000000,11400.000000,9902.000000,8179.000000,15800.000000