In [1]:
import pandas as pd
import os
import math

In [2]:
users = pd.read_csv("./results/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["C1", "C2", "C3", "C4"]

# path

In [3]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_id in users["uuid"]:

        path_length = 0
        df_path = task_dict[user_id]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_C1,path_C2,path_C3,path_C4
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,2851.863988,2420.341564,1872.954802,2229.886137
1,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,6871.093181,4157.161260,3120.664923,1618.326648
2,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,3457.397146,1185.723163,1967.255737,4104.787427
3,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,2160.748609,1963.294155,2146.362506,1510.036611
4,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2124.084796,2723.397703,2516.141743,1424.325947
5,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2404.870482,1851.809047,1700.914064,1468.441494
6,649aba058c612604f08fde63,23,female,touchpad,3,23,True,2365.702815,1224.319347,1713.443864,1193.647891
7,649b38738c611b846db1a58d,25,female,mouse,1,23,True,1943.086430,1151.882865,2055.844584,1521.562870
8,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3463.591277,1043.732323,3071.380074,2296.296357
9,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,2480.933842,1894.568581,1974.990181,1349.472442
10,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,2503.519831,1051.079189,2175.211451,1374.655196
11,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2136.246641,1940.412789,1732.360967,1396.180718

# time

In [4]:
for task in tasks:
    
    task_times = []

    for user in users["uuid"]:
        df = pd.read_csv("data/tracking_files/" + user + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"])

    users["time_" + task] = task_times

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_C1,path_C2,path_C3,path_C4,time_C1,time_C2,time_C3,time_C4
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,2851.863988,2420.341564,1872.954802,2229.886137,7289,11680,3927,3865
1,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,6871.093181,4157.161260,3120.664923,1618.326648,7877,6042,5970,1807
2,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,3457.397146,1185.723163,1967.255737,4104.787427,11393,5384,3822,6762
3,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,2160.748609,1963.294155,2146.362506,1510.036611,4866,3991,5486,3520
4,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2124.084796,2723.397703,2516.141743,1424.325947,12638,15038,17267,10542
5,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2404.870482,1851.809047,1700.914064,1468.441494,6440,5488,4193,8096
6,649aba058c612604f08fde63,23,female,touchpad,3,23,True,2365.702815,1224.319347,1713.443864,1193.647891,6374,7204,6105,3991
7,649b38738c611b846db1a58d,25,female,mouse,1,23,True,1943.086430,1151.882865,2055.844584,1521.562870,4028,3128,3539,4923
8,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3463.591277,1043.732323,3071.380074,2296.296357,3584,4041,3833,8457
9,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,2480.933842,1894.568581,1974.990181,1349.472442,5128,4663,3634,6187
10,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,2503.519831,1051.079189,2175.211451,1374.655196,4525,4374,4890,6508
11,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2136.246641,1940.412789,1732.360967,1396.180718,5078,6472,5163,4260

# describe

In [5]:
users.describe()

,age,sorting_option,num_of_files,path_C1,path_C2,path_C3,path_C4,time_C1,time_C2,time_C3,time_C4
count,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,38.666667,1.750000,23.0,2896.928253,1883.976832,2170.627075,1790.634978,6601.666667,6458.750000,5652.416667,5743.166667
std,17.195842,0.866025,0.0,1345.399268,905.975228,489.625045,803.537872,2846.360909,3494.044026,3770.229519,2480.018872
min,23.000000,1.000000,23.0,1943.086430,1043.732323,1700.914064,1193.647891,3584.000000,3128.000000,3539.000000,1807.000000
25%,25.000000,1.000000,23.0,2154.623117,1177.263088,1837.806344,1390.799338,4780.750000,4290.750000,3830.250000,3959.500000
50%,25.500000,1.500000,23.0,2442.902162,1873.188814,2015.417383,1489.239052,5751.000000,5436.000000,4541.500000,5555.000000
75%,56.000000,2.250000,23.0,3003.247278,2077.556007,2260.444024,1771.216520,7436.000000,6655.000000,5607.000000,7095.500000
max,61.000000,3.000000,23.0,6871.093181,4157.161260,3120.664923,4104.787427,12638.000000,15038.000000,17267.000000,10542.000000

# Speichern

In [6]:
users.to_csv("./results/analysis_C.csv", index=False)