In [1]:
import pandas as pd
import os
import math

In [2]:
users = pd.read_csv("./results/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["B1", "B2", "B3", "B4"]

# path

In [3]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_id in users["uuid"]:

        path_length = 0
        df_path = task_dict[user_id]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_B1,path_B2,path_B3,path_B4
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,485.995152,615.867521,1293.998245,470.779942
1,649afe9b8c617b636a488066,41,male,mouse,2,23,True,497.557244,813.388829,896.230532,415.819043
2,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,495.241464,606.114256,2758.115777,495.503695
3,649c7ae28c61679274caf9c6,26,male,touchpad,2,23,True,1175.277461,572.084784,660.231020,394.780679
4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,889.394919,1032.510207,756.786114,1015.231860
5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,611.757516,604.257801,698.587485,483.160859
6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,1450.137929,924.126770,2036.448044,418.735112
7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,600.655147,682.194728,715.726316,1445.843399
8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,1459.326768,1026.184221,1657.984016,473.770494
9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,516.955042,666.459670,936.593551,616.468393
10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,536.021777,799.945140,791.968348,381.031490
11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,437.078824,692.271807,808.595234,531.622264
12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,477.578898,817.486924,797.726046,464.402506
13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,469.125575,590.206913,1336.023549,414.850296
14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,458.050667,570.514777,1200.704209,403.671491
15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,490.917668,743.988943,692.599804,436.208906
16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,1339.989800,634.178473,868.196413,440.151425
17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2911.173611,578.367265,738.837941,408.204060

# time

In [4]:
for task in tasks:
    
    task_times = []

    for user in users["uuid"]:
        df = pd.read_csv("data/tracking_files/" + user + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"])

    users["time_" + task] = task_times

users

,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_B1,path_B2,path_B3,path_B4,time_B1,time_B2,time_B3,time_B4
0,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,485.995152,615.867521,1293.998245,470.779942,2353,4041,3024,5216
1,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,495.241464,606.114256,2758.115777,495.503695,2114,1495,5313,1528
2,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,889.394919,1032.510207,756.786114,1015.231860,2176,2367,2187,4649
3,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,611.757516,604.257801,698.587485,483.160859,3267,2390,1834,1563
4,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,600.655147,682.194728,715.726316,1445.843399,4683,6276,5382,9101
5,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,516.955042,666.459670,936.593551,616.468393,5489,5361,3833,10361
6,649aba058c612604f08fde63,23,female,touchpad,3,23,True,437.078824,692.271807,808.595234,531.622264,2448,3774,5072,2945
7,649b38738c611b846db1a58d,25,female,mouse,1,23,True,477.578898,817.486924,797.726046,464.402506,3594,1742,4908,2328
8,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,469.125575,590.206913,1336.023549,414.850296,2600,2368,2969,2072
9,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,458.050667,570.514777,1200.704209,403.671491,4177,2794,3254,1899
10,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,1339.989800,634.178473,868.196413,440.151425,4076,1474,4622,4458
11,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2911.173611,578.367265,738.837941,408.204060,5527,2554,3617,3049

# describe

In [5]:
users.describe()

,age,sorting_option,num_of_files,path_B1,path_B2,path_B3,path_B4,time_B1,time_B2,time_B3,time_B4
count,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,38.666667,1.750000,23.0,807.749718,674.202528,1075.824240,599.157516,3542.000000,3053.000000,3834.583333,4097.416667
std,17.195842,0.866025,0.0,711.257081,131.732899,576.791361,314.443906,1250.552096,1523.911713,1220.701323,2915.045780
min,23.000000,1.000000,23.0,437.078824,570.514777,698.587485,403.671491,2114.000000,1474.000000,1834.000000,1528.000000
25%,25.000000,1.000000,23.0,475.465567,600.745079,752.299071,433.826143,2424.250000,2210.750000,3010.250000,2028.750000
50%,25.500000,1.500000,23.0,506.098253,625.022997,838.395824,476.970401,3430.500000,2472.000000,3725.000000,2997.000000
75%,56.000000,2.250000,23.0,681.166867,684.713998,1224.027718,552.833796,4303.500000,3840.750000,4949.000000,4790.750000
max,61.000000,3.000000,23.0,2911.173611,1032.510207,2758.115777,1445.843399,5527.000000,6276.000000,5382.000000,10361.000000

# Speichern

In [6]:
users.to_csv("./results/analysis_B.csv", index=False)