In [2]:
import pandas as pd
import os
import math
import plotly.express as px
import plotly.graph_objects as go

In [3]:
users = pd.read_csv("./results/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["B1", "B2", "B3", "B4"]
users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True

# path

In [4]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_nr in users["nr"]:
        
        path_length = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_B1,path_B2,path_B3,path_B4
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,485.995152,615.867521,1293.998245,470.779942
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,497.557244,813.388829,896.230532,415.819043
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,495.241464,606.114256,2758.115777,495.503695
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,889.394919,1032.510207,756.786114,1015.231860
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,611.757516,604.257801,698.587485,483.160859
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,1450.137929,924.126770,2036.448044,418.735112
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,600.655147,682.194728,715.726316,1445.843399
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,1459.326768,1026.184221,1657.984016,473.770494
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,516.955042,666.459670,936.593551,616.468393
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,536.021777,799.945140,791.968348,381.031490
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,437.078824,692.271807,808.595234,531.622264
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,477.578898,817.486924,797.726046,464.402506
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,469.125575,590.206913,1336.023549,414.850296
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,458.050667,570.514777,1200.704209,403.671491
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,490.917668,743.988943,692.599804,436.208906
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,1339.989800,634.178473,868.196413,440.151425
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2911.173611,578.367265,738.837941,408.204060

# time

In [5]:
for task in tasks:
    
    task_times = []

    for user in users["nr"]:
        df = pd.read_csv("data/tracking_files/" + str(user) + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"] / 1000)

    users["time_" + task] = task_times

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_B1,path_B2,path_B3,path_B4,time_B1,time_B2,time_B3,time_B4
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,485.995152,615.867521,1293.998245,470.779942,2.353,4.041,3.024,5.216
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,497.557244,813.388829,896.230532,415.819043,3.239,2.502,6.506,5.569
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,495.241464,606.114256,2758.115777,495.503695,2.114,1.495,5.313,1.528
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,889.394919,1032.510207,756.786114,1015.231860,2.176,2.367,2.187,4.649
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,611.757516,604.257801,698.587485,483.160859,3.267,2.390,1.834,1.563
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,1450.137929,924.126770,2036.448044,418.735112,2.762,2.396,3.787,1.169
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,600.655147,682.194728,715.726316,1445.843399,4.683,6.276,5.382,9.101
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,1459.326768,1026.184221,1657.984016,473.770494,4.824,2.960,4.101,2.742
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,516.955042,666.459670,936.593551,616.468393,5.489,5.361,3.833,10.361
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,536.021777,799.945140,791.968348,381.031490,2.961,6.146,4.437,2.977
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,437.078824,692.271807,808.595234,531.622264,2.448,3.774,5.072,2.945
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,477.578898,817.486924,797.726046,464.402506,3.594,1.742,4.908,2.328
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,469.125575,590.206913,1336.023549,414.850296,2.600,2.368,2.969,2.072
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,458.050667,570.514777,1200.704209,403.671491,4.177,2.794,3.254,1.899
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,490.917668,743.988943,692.599804,436.208906,3.422,2.368,3.124,2.056
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,1339.989800,634.178473,868.196413,440.151425,4.076,1.474,4.622,4.458
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2911.173611,578.367265,738.837941,408.204060,5.527,2.554,3.617,3.049

# Kontrolle

nicht nötig, da man ohne Klick auf "Ok" gar nicht weiter kommt.

# Strecke pro Sekunde

In [6]:
for task in tasks:
    users["v_" + task] = users["path_" + task] / users["time_" + task] 

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_B1,path_B2,path_B3,path_B4,time_B1,time_B2,time_B3,time_B4,v_B1,v_B2,v_B3,v_B4
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,485.995152,615.867521,1293.998245,470.779942,2.353,4.041,3.024,5.216,206.542776,152.404732,427.909472,90.256891
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,497.557244,813.388829,896.230532,415.819043,3.239,2.502,6.506,5.569,153.614462,325.095455,137.754462,74.666734
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,495.241464,606.114256,2758.115777,495.503695,2.114,1.495,5.313,1.528,234.267485,405.427596,519.125876,324.282523
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,889.394919,1032.510207,756.786114,1015.231860,2.176,2.367,2.187,4.649,408.729283,436.210480,346.038461,218.376395
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,611.757516,604.257801,698.587485,483.160859,3.267,2.390,1.834,1.563,187.253602,252.827532,380.909207,309.124030
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,1450.137929,924.126770,2036.448044,418.735112,2.762,2.396,3.787,1.169,525.031835,385.695647,537.747041,358.199411
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,600.655147,682.194728,715.726316,1445.843399,4.683,6.276,5.382,9.101,128.262897,108.698969,132.985194,158.866432
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,1459.326768,1026.184221,1657.984016,473.770494,4.824,2.960,4.101,2.742,302.513841,346.683858,404.287739,172.782821
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,516.955042,666.459670,936.593551,616.468393,5.489,5.361,3.833,10.361,94.180186,124.316297,244.350000,59.498928
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,536.021777,799.945140,791.968348,381.031490,2.961,6.146,4.437,2.977,181.027280,130.157035,178.491852,127.991767
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,437.078824,692.271807,808.595234,531.622264,2.448,3.774,5.072,2.945,178.545271,183.431851,159.423351,180.516898
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,477.578898,817.486924,797.726046,464.402506,3.594,1.742,4.908,2.328,132.882276,469.280668,162.535869,199.485613
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,469.125575,590.206913,1336.023549,414.850296,2.600,2.368,2.969,2.072,180.432913,249.242784,449.991091,200.217324
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,458.050667,570.514777,1200.704209,403.671491,4.177,2.794,3.254,1.899,109.660203,204.192834,368.993303,212.570559
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,490.917668,743.988943,692.599804,436.208906,3.422,2.368,3.124,2.056,143.459284,314.184520,221.702882,212.163865
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,1339.989800,634.178473,868.196413,440.151425,4.076,1.474,4.622,4.458,328.751178,430.243198,187.839986,98.732935
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2911.173611,578.367265,738.837941,408.204060,5.527,2.554,3.617,3.049,526.718584,226.455468,204.268162,133.881292

# Describe

In [7]:
users.describe()

,nr,age,sorting_option,num_of_files,path_B1,path_B2,path_B3,path_B4,time_B1,time_B2,time_B3,time_B4,v_B1,v_B2,v_B3,v_B4
count,17.000000,17.000000,17.000000,17.0,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,9.000000,36.764706,1.764706,23.0,830.997530,729.297897,1116.771860,547.967955,3.512471,3.118118,3.998235,3.746000,236.580786,279.091113,297.903173,184.212613
std,5.049752,15.254218,0.831370,0.0,645.330265,151.181398,567.475998,273.758187,1.114775,1.505263,1.225089,2.614551,136.298670,119.707679,138.346679,86.206468
min,1.000000,19.000000,1.000000,23.0,437.078824,570.514777,692.599804,381.031490,2.114000,1.474000,1.834000,1.169000,94.180186,108.698969,132.985194,59.498928
25%,5.000000,25.000000,1.000000,23.0,485.995152,606.114256,756.786114,415.819043,2.600000,2.368000,3.124000,2.056000,143.459284,183.431851,178.491852,127.991767
50%,9.000000,29.000000,2.000000,23.0,516.955042,682.194728,868.196413,464.402506,3.267000,2.502000,3.833000,2.945000,181.027280,252.827532,244.350000,180.516898
75%,13.000000,54.000000,2.000000,23.0,889.394919,813.388829,1293.998245,495.503695,4.177000,3.774000,4.908000,4.649000,302.513841,385.695647,404.287739,212.570559
max,17.000000,61.000000,3.000000,23.0,2911.173611,1032.510207,2758.115777,1445.843399,5.527000,6.276000,6.506000,10.361000,526.718584,469.280668,537.747041,358.199411

In [7]:

fig = go.Figure()

fig = fig.add_trace(go.Scatter(x = users["time_E1"],
                                y = users["path_E1"], 
                                name = "E1",
                                mode = "markers"
                                    ))

fig = fig.add_trace(go.Scatter(x = users["time_E2"],
                                y = users["path_E2"], 
                                name = "E2",
                                mode = "markers"
                                    ))

fig = fig.add_trace(go.Scatter(x = users["time_E3"],
                                y = users["path_E3"], 
                                name = "E3",
                                mode = "markers"
                                    ))

fig.show()

KeyError: 'time_E1'

# Speichern

In [ ]:
users.to_csv("./results/analysis_E.csv", index=False)