In [27]:
import pandas as pd
import os
import math
import plotly.express as px
import plotly.graph_objects as go

In [28]:
users = pd.read_csv("./results/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", 
         "B1", "B2", "B3", "B4", 
         "C1", "C2", "C3", "C4", 
         "D1", "D2", 
         "E1", "E2", "E3", 
         "F1", "F2", "F3"]
         
users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True

# path

In [29]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_nr in users["nr"]:
        
        path_length = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,path_C3,path_C4,path_D1,path_D2,path_E1,path_E2,path_E3,path_F1,path_F2,path_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,1872.954802,2229.886137,414.756640,351.410796,622.722904,492.031700,515.905771,950.938547,875.354547,1441.839664
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,1777.781284,1199.111788,378.299792,243.362310,504.184470,452.645191,438.915928,450.533436,637.377266,518.718348
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,3120.664923,1618.326648,593.207263,2096.347318,514.016720,488.780575,593.217099,785.396508,728.063684,649.676250
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,1967.255737,4104.787427,1621.081970,561.630888,467.307732,452.510325,468.088532,596.366156,740.243115,702.453166
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,2146.362506,1510.036611,463.608536,270.799086,492.644046,450.760499,467.896643,641.223339,645.234367,756.770399
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,2255.692818,1767.882942,424.320678,284.087921,519.098440,524.811476,442.859898,1168.867175,908.517308,553.460750
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,2516.141743,1424.325947,1991.304496,650.573178,757.704066,655.783794,575.245990,714.924015,884.963711,1630.297685
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,1777.655993,1218.342182,754.213950,475.641607,451.605138,464.128626,498.273308,556.459741,627.720516,559.491683
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,1700.914064,1468.441494,2006.627258,7426.651857,890.121131,479.531061,713.576041,1114.057519,1156.777835,596.028811
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,1983.556411,1621.486545,1275.104820,230.555065,755.765691,462.734516,500.180918,1528.353084,774.289740,725.949738
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,1713.443864,1193.647891,570.716731,367.124364,523.808668,525.000092,490.811323,709.494589,649.799945,601.564415
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,2055.844584,1521.562870,531.375989,299.319710,531.727165,440.324626,493.590238,462.024609,634.537420,596.069790
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,3071.380074,2296.296357,451.387838,358.202311,583.854219,644.263257,699.453714,758.067394,748.309167,642.897014
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,1974.990181,1349.472442,466.824542,232.031669,471.314932,434.232297,453.121944,448.560994,739.526833,544.407517
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,2003.862854,1235.058561,509.957203,739.096468,725.349891,612.039960,543.856419,1072.010426,687.622957,740.435063
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,2175.211451,1374.655196,473.831069,288.002343,507.261573,563.209412,478.474402,495.727829,747.516437,651.115120
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,1732.360967,1396.180718,386.462686,225.405891,500.209287,445.197928,522.551026,488.747958,621.934381,605.022259

# time

In [30]:
for task in tasks:
    
    task_times = []

    for user in users["nr"]:
        df = pd.read_csv("data/tracking_files/" + str(user) + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"] / 1000)

    users["time_" + task] = task_times

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,time_C3,time_C4,time_D1,time_D2,time_E1,time_E2,time_E3,time_F1,time_F2,time_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,3.927,3.865,2.351,3.305,3.809,1.697,1.400,8.224,10.033,7.729
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,5.256,3.242,2.993,2.524,2.204,2.305,1.369,3.599,4.718,4.808
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,5.970,1.807,2.243,3.864,1.070,1.295,1.031,2.495,2.578,3.463
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,3.822,6.762,3.954,3.225,2.102,2.759,1.479,4.070,3.699,4.802
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,5.486,3.520,1.929,1.854,1.460,1.441,1.658,4.414,5.010,2.654
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,3.236,4.121,1.614,1.956,1.583,1.720,1.388,7.121,4.961,2.420
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,17.267,10.542,13.999,8.570,4.874,7.537,5.068,10.633,19.594,9.720
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,4.311,7.964,2.290,1.875,2.041,1.933,1.995,5.972,5.235,6.499
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,4.193,8.096,8.080,18.265,2.424,2.481,1.911,6.657,6.361,9.282
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,5.536,4.905,6.093,14.895,8.075,3.298,2.869,22.116,6.473,7.407
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,6.105,3.991,4.016,3.490,4.433,2.600,3.917,14.702,7.511,6.812
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,3.539,4.923,2.734,1.813,2.349,3.089,2.261,6.407,5.444,4.211
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,3.833,8.457,1.664,1.937,1.463,1.833,3.369,4.113,5.570,4.136
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,3.634,6.187,2.820,1.631,1.128,1.166,1.955,5.331,8.256,4.522
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,7.978,2.939,2.049,7.306,2.805,4.350,1.673,3.635,6.635,7.205
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,4.890,6.508,2.686,1.478,1.826,2.065,1.748,4.596,4.093,4.335
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,5.163,4.260,1.772,4.816,3.396,1.665,1.880,10.954,5.269,5.594

# DuGe

In [31]:
for task in tasks:
    users["v_" + task] = users["path_" + task] / users["time_" + task] 

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,v_C3,v_C4,v_D1,v_D2,v_E1,v_E2,v_E3,v_F1,v_F2,v_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,476.942909,576.943373,176.417116,106.327019,163.487242,289.942074,368.504122,115.629687,87.247538,186.549316
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,338.238448,369.867917,126.394852,96.419299,228.758834,196.375354,320.610612,125.182950,135.094800,107.886512
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,522.724443,895.587520,264.470469,542.532950,480.389458,377.436737,575.380309,314.788180,282.414152,187.605039
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,514.718926,607.037478,409.985324,174.149113,222.315762,164.012441,316.489879,146.527311,200.119793,146.283458
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,391.243621,428.987674,240.336203,146.062074,337.427429,312.810894,282.205454,145.270353,128.789295,285.143331
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,697.062057,428.993677,262.900048,145.239223,327.920682,305.122951,319.063327,164.143684,183.131890,228.702789
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,145.719682,135.109652,142.246196,75.912856,155.458364,87.008597,113.505523,67.236341,45.165036,167.726099
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,412.353513,152.981188,329.351070,253.675524,221.266604,240.107929,249.761057,93.178121,119.908408,86.088888
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,405.655632,181.378643,248.344958,406.605631,367.211688,193.281363,373.404522,167.351287,181.854714,64.213403
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,358.301375,330.578297,209.273727,15.478688,93.593274,140.307616,174.339811,69.106216,119.618375,98.008605
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,280.662386,299.084914,142.110740,105.193227,118.161215,201.923112,125.302865,48.258372,86.513107,88.309515
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,580.911157,309.072287,194.358445,165.096365,226.363204,142.546010,218.306165,72.112472,116.557204,141.550651
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,801.299263,271.526115,271.266730,184.926335,399.080122,351.480228,207.614638,184.310088,134.346350,155.439317
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,543.475559,218.114182,165.540618,142.263439,417.832386,372.411919,231.775930,84.141999,89.574471,120.390871
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,251.173584,420.230882,248.881016,101.162944,258.591762,140.698841,325.078553,294.913460,103.635713,102.766837
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,444.828518,211.225445,176.407695,194.859501,277.799328,272.740635,273.726774,107.860711,182.632894,150.199566
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,335.533792,327.741953,218.094067,46.803549,147.293665,267.386143,277.952673,44.618218,118.036512,108.155570

In [32]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("path_F")]
users[columns].describe()

           path_F1      path_F2      path_F3
count    17.000000    17.000000    17.000000
mean    761.279607   753.399366   736.246922
std     309.151083   138.719347   310.823008
min     448.560994   621.934381   518.718348
25%     495.727829   645.234367   596.028811
50%     709.494589   739.526833   642.897014
75%     950.938547   774.289740   725.949738
max    1528.353084  1156.777835  1630.297685

In [33]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_F")]
users[columns].describe()

         time_F1    time_F2    time_F3
count  17.000000  17.000000  17.000000
mean    7.355235   6.555294   5.623471
std     4.955411   3.790679   2.159721
min     2.495000   2.578000   2.420000
25%     4.113000   4.961000   4.211000
50%     5.972000   5.444000   4.808000
75%     8.224000   6.635000   7.205000
max    22.116000  19.594000   9.720000

In [34]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("v_F")]
users[columns].describe()

             v_F1        v_F2        v_F3
count   17.000000   17.000000   17.000000
mean   132.037027  136.155309  142.648222
std     77.636216   55.683153   56.625427
min     44.618218   45.165036   64.213403
25%     72.112472  103.635713  102.766837
50%    115.629687  119.908408  141.550651
75%    164.143684  181.854714  167.726099
max    314.788180  282.414152  285.143331

# Anzahl Clicks

In [35]:
for task in tasks:
    
    task_num_clicks = []

    for user in users["nr"]:
        df = pd.read_csv("data/tracking_files/" + str(user) + "_" + task + ".csv")
        task_num_clicks.append(df['action'].value_counts()['c'])

    users["num_clicks_" + task] = task_num_clicks

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,num_clicks_C3,num_clicks_C4,num_clicks_D1,num_clicks_D2,num_clicks_E1,num_clicks_E2,num_clicks_E3,num_clicks_F1,num_clicks_F2,num_clicks_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,3,3,2,2,2,2,2,3,3,3
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,3,3,2,2,2,2,2,3,3,3
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,3,3,2,2,2,2,2,3,3,3
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,3,3,3,2,2,2,2,3,3,3
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,3,3,2,2,2,2,2,3,3,3
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,3,3,2,2,2,2,2,3,3,3
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,3,3,2,2,2,2,2,3,3,3
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,3,3,2,2,2,2,2,3,3,3
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,3,3,3,4,2,2,2,3,3,4
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,3,3,2,2,2,2,2,3,3,3
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,3,3,2,2,2,2,2,3,3,3
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,3,3,2,2,2,2,2,3,3,3
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,3,3,2,2,2,2,2,3,3,3
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,3,3,2,2,2,2,2,3,3,3
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,3,3,2,2,2,2,2,3,3,3
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,3,3,2,2,2,2,2,3,3,3
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,3,3,2,2,2,2,2,3,3,3

In [36]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("num_clicks_")]
users[columns].value_counts()

num_clicks_A1  num_clicks_A2  num_clicks_A3  num_clicks_A4  num_clicks_A5  num_clicks_A6  num_clicks_A7  num_clicks_B1  num_clicks_B2  num_clicks_B3  num_clicks_B4  num_clicks_C1  num_clicks_C2  num_clicks_C3  num_clicks_C4  num_clicks_D1  num_clicks_D2  num_clicks_E1  num_clicks_E2  num_clicks_E3  num_clicks_F1  num_clicks_F2  num_clicks_F3
3              3              3              3              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                7
                                             4              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                3
                              4              3              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                2
                              3              3              3              3              3              2              2              2              2              3              3              3              3              3              4              2              2              2              3              3              4                1
               4              3              3              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                1
4              3              3              3              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                1
                                             4              3              3              3              2              2              2              2              3              3              3              3              2              2              2              2              2              3              3              3                1
5              3              3              3              3              3              3              2              2              2              2              3              3              3              3              3              2              2              2              2              3              3              3                1
dtype: int64

# Zeit in Ruhe

In [37]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    times_ruhe = []

    for user_nr in users["nr"]:
        
        time_ruhe = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            dms = df_path['ms'].iloc[i] - df_path['ms'].iloc[i-1]
            if dms > 500:
                time_ruhe += dms
        times_ruhe.append(time_ruhe / 1000)

    users["time_ruhe_" + task] = times_ruhe
    users["time_ruhe_pr_" + task] = users["time_ruhe_" + task] / users["time_" + task] * 100

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,time_ruhe_E2,time_ruhe_pr_E2,time_ruhe_E3,time_ruhe_pr_E3,time_ruhe_F1,time_ruhe_pr_F1,time_ruhe_F2,time_ruhe_pr_F2,time_ruhe_F3,time_ruhe_pr_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,0.514,30.288745,0.000,0.000000,4.187,50.911965,7.865,78.391309,3.942,51.002717
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,1.824,79.132321,0.000,0.000000,0.860,23.895527,3.235,68.567189,3.029,62.999168
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,0.000,0.000000,0.000,0.000000,0.000,0.000000,1.119,43.405741,1.590,45.913947
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,1.570,56.904676,0.000,0.000000,1.819,44.692875,1.629,44.038929,2.575,53.623490
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,0.000,0.000000,0.000,0.000000,2.066,46.805618,2.728,54.451098,0.546,20.572720
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,0.000,0.000000,0.000,0.000000,2.218,31.147311,1.911,38.520460,0.531,21.942149
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,6.082,80.695237,3.466,68.389897,7.839,73.723314,17.345,88.521997,6.783,69.783951
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,1.269,65.649250,0.680,34.085213,4.042,67.682518,3.353,64.049666,3.958,60.901677
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,1.096,44.175736,0.000,0.000000,3.902,58.614992,3.923,61.672693,7.069,76.158156
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,2.338,70.891449,1.117,38.933426,20.250,91.562670,4.322,66.769659,5.348,72.201971
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,0.675,25.961538,1.306,33.341843,9.509,64.678275,5.694,75.808814,4.896,71.873165
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,2.032,65.781806,1.032,45.643521,4.923,76.837834,4.006,73.585599,2.112,50.154358
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,0.000,0.000000,1.177,34.936183,2.617,63.627522,3.798,68.186715,2.047,49.492263
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,0.000,0.000000,0.913,46.700767,2.494,46.782968,5.817,70.457849,2.383,52.697921
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,1.664,38.252874,0.000,0.000000,0.829,22.806052,5.085,76.639035,4.633,64.302568
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,0.700,33.898305,0.678,38.787185,3.239,70.474326,1.515,37.014415,3.035,70.011534
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,0.558,33.513514,0.627,33.351064,8.215,74.995435,3.192,60.580755,3.699,66.124419

In [38]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_ruhe_A")]
users[columns].describe()

,time_ruhe_A1,time_ruhe_A2,time_ruhe_A3,time_ruhe_A4,time_ruhe_A5,time_ruhe_A6,time_ruhe_A7
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,2.371118,2.946588,2.329647,2.605529,1.461765,1.824176,2.643412
std,2.053450,3.146500,1.677779,2.488052,1.305199,1.542704,2.724725
min,0.000000,0.505000,0.869000,0.000000,0.000000,0.000000,0.000000
25%,1.407000,1.448000,1.354000,1.147000,0.523000,0.861000,1.031000
50%,1.871000,1.874000,1.725000,1.840000,1.478000,1.465000,1.671000
75%,3.837000,3.010000,2.700000,2.739000,1.974000,3.047000,2.832000
max,6.574000,12.658000,7.411000,8.387000,5.067000,4.970000,10.977000

In [39]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_ruhe_pr_F")]
users[columns].describe()

       time_ruhe_pr_F1  time_ruhe_pr_F2  time_ruhe_pr_F3
count        17.000000        17.000000        17.000000
mean         53.484659        62.980113        56.456246
std          23.667015        14.953852        16.168739
min           0.000000        37.014415        20.572720
25%          44.692875        54.451098        50.154358
50%          58.614992        66.769659        60.901677
75%          70.474326        73.585599        69.783951
max          91.562670        88.521997        76.158156

In [56]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_ruhe_pr_")]
users["time_ruhe_pr_mean"] = users[columns].mean(axis=1)
users[["nr", "time_ruhe_pr_mean"]]

    nr  time_ruhe_pr_mean
0    1          46.368311
1    2          52.659528
2    3          10.767458
3    4          25.326518
4    5          23.092832
5    6           9.281499
6    7          71.042105
7    8          41.939591
8    9          40.073413
9   10          62.268384
10  11          47.468371
11  12          54.286106
12  13          36.526691
13  14          45.139610
14  15          50.571100
15  16          47.498366
16  17          49.356729

In [58]:
users[["nr", "time_ruhe_pr_mean"]].describe()

              nr  time_ruhe_pr_mean
count  17.000000          17.000000
mean    9.000000          41.980389
std     5.049752          16.678221
min     1.000000           9.281499
25%     5.000000          36.526691
50%     9.000000          46.368311
75%    13.000000          50.571100
max    17.000000          71.042105

# Aufgaben mit Fertig-Button

In [40]:
tasks = ["A1", "A2", "A3", "A4", "A5", "A6", "A7",
         "C1", "C2", "C3", "C4", 
         "F1", "F2", "F3"]

In [41]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []
    card_click_times = []

    for user_nr in users["nr"]:

        df_path = task_dict[str(user_nr)]
        card_click_time = df_path[df_path["action"] == "c"].iloc[-2]["ms"]
        card_click_times.append(card_click_time)

    print(card_click_times)    

    for user_nr in users["nr"]:
        
        path_length = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            if df_path["ms"].iloc[i] < card_click_times[user_nr-1]:
                dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
                dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
                segment_length = math.sqrt(dx**2 + dy**2)
                path_length += segment_length
        path_lengths.append(path_length)

    if task.startswith("C"):
        users["path_to_click_" + task] = path_lengths
        
    users["time_to_click_" + task] = card_click_times
    users["time_to_click_" + task] = users["time_to_click_" + task] / 1000
    users["time_after_click_" + task] = users["time_" + task] - users["time_to_click_" + task]

users

[2912, 7401, 3191, 4451, 2587, 3450, 5295, 3983, 4728, 4352, 3895, 2850, 2072, 2528, 6218, 5005, 3880]
[3753, 3643, 4722, 3138, 2414, 1727, 10832, 2234, 3311, 4073, 2677, 3062, 3095, 3322, 13162, 2364, 3616]
[2943, 5149, 5786, 2417, 2646, 2416, 5036, 2819, 3831, 4281, 4441, 4090, 3722, 2834, 4795, 2542, 5261]
[3879, 3914, 2311, 2702, 2493, 3878, 5224, 5640, 5527, 10431, 4385, 4175, 3664, 3114, 5602, 2683, 4453]
[3409, 3698, 1859, 2591, 2226, 3746, 7638, 4821, 3048, 6093, 4821, 2880, 3201, 2749, 2623, 2400, 3362]
[3271, 3954, 1639, 3032, 2495, 2462, 4342, 4005, 3657, 7799, 6284, 3124, 2775, 2751, 2725, 3031, 4309]
[2672, 3678, 1456, 3138, 3338, 3530, 14280, 4202, 3047, 4259, 3226, 4828, 4144, 2998, 7062, 3629, 2875]
[5984, 8630, 6935, 7310, 3464, 3700, 9394, 5356, 4704, 3951, 4606, 3024, 2463, 3327, 6392, 3210, 3500]
[7407, 4803, 5564, 4055, 3021, 5744, 13810, 2087, 3736, 5120, 4602, 2520, 3087, 3616, 4695, 3515, 4222]
[2663, 3037, 5175, 1954, 4405, 1708, 14434, 2167, 2535, 4359, 2823, 2323, 2648, 1895, 6405, 2847, 3092]
[2984, 1832, 1114, 5690, 1916, 2420, 8758, 6059, 6863, 3643, 2215, 3353, 6689, 4069, 1828, 5250, 2400]
[4879, 1661, 703, 1571, 1364, 1876, 4050, 2453, 1344, 6582, 5138, 1388, 1071, 1197, 1328, 1029, 2835]
[1671, 1772, 688, 1380, 1090, 1774, 11963, 1549, 1442, 2723, 1882, 1562, 2369, 4612, 1538, 1144, 1125]
[3376, 1853, 1436, 1448, 1202, 1106, 3963, 1328, 3127, 3490, 2353, 902, 1265, 1392, 1720, 1109, 1701]

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,time_after_click_C3,path_to_click_C4,time_to_click_C4,time_after_click_C4,time_to_click_F1,time_after_click_F1,time_to_click_F2,time_after_click_F2,time_to_click_F3,time_after_click_F3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,1.264,1631.046412,2.984,0.881,4.879,3.345,1.671,8.362,3.376,4.353
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,2.219,562.049690,1.832,1.410,1.661,1.938,1.772,2.946,1.853,2.955
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,0.795,1010.667310,1.114,0.693,0.703,1.792,0.688,1.890,1.436,2.027
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,1.868,3456.641603,5.690,1.072,1.571,2.499,1.380,2.319,1.448,3.354
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,1.081,770.378664,1.916,1.604,1.364,3.050,1.090,3.920,1.202,1.452
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,1.528,798.782827,2.420,1.701,1.876,5.245,1.774,3.187,1.106,1.314
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,2.833,783.797226,8.758,1.784,4.050,6.583,11.963,7.631,3.963,5.757
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,2.144,573.300708,6.059,1.905,2.453,3.519,1.549,3.686,1.328,5.171
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,1.658,749.248423,6.863,1.233,1.344,5.313,1.442,4.919,3.127,6.155
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,1.177,1004.840144,3.643,1.262,6.582,15.534,2.723,3.750,3.490,3.917
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,3.282,544.102569,2.215,1.776,5.138,9.564,1.882,5.629,2.353,4.459
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,1.216,724.131958,3.353,1.570,1.388,5.019,1.562,3.882,0.902,3.309
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,1.185,1160.402444,6.689,1.768,1.071,3.042,2.369,3.201,1.265,2.871
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,1.739,656.204683,4.069,2.118,1.197,4.134,4.612,3.644,1.392,3.130
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,1.573,602.481365,1.828,1.111,1.328,2.307,1.538,5.097,1.720,5.485
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,2.043,753.568951,5.250,1.258,1.029,3.567,1.144,2.949,1.109,3.226
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,2.071,751.709663,2.400,1.860,2.835,8.119,1.125,4.144,1.701,3.893

In [42]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("path_to_click_")]
users[columns].describe()

       path_to_click_C1  path_to_click_C2  path_to_click_C3  path_to_click_C4
count         17.000000         17.000000         17.000000         17.000000
mean        1406.395358       1502.789300        861.703711        972.550273
std         1217.378329        901.805327        445.992394        693.974502
min          676.124023        681.664467        532.418683        544.102569
25%          744.500910        834.783657        595.726583        656.204683
50%          820.660469       1302.936613        698.994696        753.568951
75%         1585.832336       1615.843263        847.569843       1004.840144
max         5493.360475       3833.743678       1996.417566       3456.641603

In [43]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_to_click_")]
users[columns].describe()

,time_to_click_A1,time_to_click_A2,time_to_click_A3,time_to_click_A4,time_to_click_A5,time_to_click_A6,time_to_click_A7,time_to_click_C1,time_to_click_C2,time_to_click_C3,time_to_click_C4,time_to_click_F1,time_to_click_F2,time_to_click_F3
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,4.046941,4.185000,3.824059,4.357353,3.597941,3.626765,4.256588,5.055882,4.800235,3.792353,3.946059,2.380529,2.369647,1.927706
std,1.400060,3.056785,1.132259,1.906153,1.492988,1.493297,2.832900,2.069580,2.661488,3.019352,2.216278,1.729919,2.621991,0.964428
min,2.072000,1.727000,2.416000,2.311000,1.859000,1.639000,1.456000,2.463000,2.087000,1.708000,1.114000,0.703000,0.688000,0.902000
25%,2.912000,2.677000,2.819000,3.114000,2.623000,2.751000,3.047000,3.464000,3.515000,2.323000,2.215000,1.328000,1.380000,1.265000
50%,3.895000,3.311000,3.831000,3.914000,3.201000,3.124000,3.530000,4.606000,4.222000,2.823000,3.353000,1.571000,1.562000,1.448000
75%,4.728000,3.753000,4.795000,5.224000,3.746000,4.005000,4.202000,6.392000,5.120000,4.359000,5.690000,2.835000,1.882000,2.353000
max,7.401000,13.162000,5.786000,10.431000,7.638000,7.799000,14.280000,9.394000,13.810000,14.434000,8.758000,6.582000,11.963000,3.963000

In [44]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("time_after_click_")]
users[columns].describe()

,time_after_click_A1,time_after_click_A2,time_after_click_A3,time_after_click_A4,time_after_click_A5,time_after_click_A6,time_after_click_A7,time_after_click_C1,time_after_click_C2,time_after_click_C3,time_after_click_C4,time_after_click_F1,time_after_click_F2,time_after_click_F3
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,1.908706,1.642471,1.798412,1.751647,1.518471,1.446059,1.424294,1.907176,1.853294,1.745647,1.470941,4.974706,4.185647,3.695765
std,0.927092,0.670758,0.768919,1.287456,0.448515,0.507118,0.571286,0.924650,1.393633,0.647847,0.396033,3.470620,1.722073,1.420931
min,0.754000,0.601000,0.908000,0.796000,0.848000,0.549000,0.646000,0.942000,0.478000,0.795000,0.693000,1.792000,1.890000,1.314000
25%,1.374000,1.344000,1.270000,1.049000,1.178000,1.079000,1.104000,1.305000,0.970000,1.216000,1.233000,3.042000,3.187000,2.955000
50%,1.508000,1.542000,1.662000,1.232000,1.468000,1.428000,1.400000,1.578000,1.329000,1.658000,1.570000,3.567000,3.750000,3.354000
75%,2.078000,1.770000,1.965000,1.754000,1.764000,1.799000,1.516000,2.145000,2.250000,2.071000,1.776000,5.313000,4.919000,4.459000
max,3.923000,3.618000,4.128000,6.176000,2.356000,2.426000,3.113000,4.083000,5.529000,3.282000,2.118000,15.534000,8.362000,6.155000

# Abweichung Idealpfad für Aufgabengruppe C

In [45]:
start = (715,75)

# Koordinaten (x,y) von C1, C2, C3, C4
c_coords = [(135,485),(1125,640),(350,445),(800,635)]

idealpfade = []

for task_coord in c_coords:
    dx = task_coord[0] - start[0]
    dy = task_coord[1] - start[1]
    segment = math.sqrt(dx**2 + dy**2)
    print(dx, dy, segment)
    idealpfade.append(segment)

idealpfade

-580 410 710.2816342831906
410 565 698.0866708367952
-365 370 519.7355096585185
85 560 566.4141594275341

[710.2816342831906, 698.0866708367952, 519.7355096585185, 566.4141594275341]

In [48]:
for i in range(4):
    users["path_to_click_-Idealpfad_C" + str(i+1)] = (users["path_to_click_C" + str(i+1)] / idealpfade[i] - 1) * 100

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,time_to_click_F1,time_after_click_F1,time_to_click_F2,time_after_click_F2,time_to_click_F3,time_after_click_F3,path_to_click_-Idealpfad_C1,path_to_click_-Idealpfad_C2,path_to_click_-Idealpfad_C3,path_to_click_-Idealpfad_C4
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,4.879,3.345,1.671,8.362,3.376,4.353,123.268104,198.429072,30.861040,187.960035
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,1.661,1.938,1.772,2.946,1.853,2.955,12.315834,13.752972,5.393340,-0.770544
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,0.703,1.792,0.688,1.890,1.436,2.027,673.405958,449.178754,284.121833,78.432564
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,1.571,2.499,1.380,2.319,1.448,3.354,177.230122,19.581664,63.077147,510.267513
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,1.364,3.050,1.090,3.920,1.202,1.452,4.817705,128.282925,45.043016,36.009782
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,1.876,5.245,1.774,3.187,1.106,1.314,285.038131,343.547944,28.867586,41.024516
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,4.050,6.583,11.963,7.631,3.963,5.757,15.540150,250.757211,146.002438,38.378819
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,2.453,3.519,1.549,3.686,1.328,5.171,106.997428,48.804649,2.440313,1.215815
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,1.344,5.313,1.442,4.919,3.127,6.155,4.178623,86.643961,10.170906,32.279254
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,6.582,15.534,2.723,3.750,3.490,3.917,12.766642,-2.352459,63.854387,77.403783
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,5.138,9.564,1.882,5.629,2.353,4.459,3.954520,22.041748,14.766390,-3.939095
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,1.388,5.019,1.562,3.882,0.902,3.309,-4.809024,29.992637,56.017759,27.844960
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,1.071,3.042,2.369,3.201,1.265,2.871,196.179158,9.571670,265.617033,104.868191
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,1.197,4.134,4.612,3.644,1.392,3.130,-2.946309,131.467428,8.767511,15.852450
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,1.328,2.307,1.538,5.097,1.720,5.485,7.861917,95.923798,34.490463,6.367638
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,1.029,3.567,1.144,2.949,1.109,3.226,30.868671,7.858790,44.429630,33.042040
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,2.835,8.119,1.125,4.144,1.701,3.893,19.422654,126.151373,14.621105,32.713784

In [49]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("path_to_click_-Idealpfad_C")]
users[columns].describe()

,path_to_click_-Idealpfad_C1,path_to_click_-Idealpfad_C2,path_to_click_-Idealpfad_C3,path_to_click_-Idealpfad_C4
count,17.000000,17.000000,17.000000,17.000000
mean,98.005311,115.272596,65.796582,71.703030
std,171.393750,129.182430,85.811415,122.520684
min,-4.809024,-2.352459,2.440313,-3.939095
25%,4.817705,19.581664,14.621105,15.852450
50%,15.540150,86.643961,34.490463,33.042040
75%,123.268104,131.467428,63.077147,77.403783
max,673.405958,449.178754,284.121833,510.267513

# Aufgaben ohne Fertig-Button

In [23]:
tasks = ["B1", "B2", "B3", "B4"]

In [50]:
start = (715,75)

# Koordinaten (x,y) von B1, B2, B3, B4
b_coords = [(500,470), (1125,470), (185,470), (810,470)]

idealpfade = []

for task_coord in b_coords:
    dx = task_coord[0] - start[0]
    dy = task_coord[1] - start[1]
    segment = math.sqrt(dx**2 + dy**2)
    print(dx, dy, segment)
    idealpfade.append(segment)

idealpfade

-215 395 449.7221364353772
410 395 569.3197695495916
-530 395 661.0030257116831
95 395 406.2634613154375

[449.7221364353772, 569.3197695495916, 661.0030257116831, 406.2634613154375]

In [51]:
for i in range(4):
    users["path_to_click_-Idealpfad_B" + str(i+1)] = (users["path_B" + str(i+1)] / idealpfade[i] -1) * 100

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_A1,path_A2,...,time_to_click_F3,time_after_click_F3,path_to_click_-Idealpfad_C1,path_to_click_-Idealpfad_C2,path_to_click_-Idealpfad_C3,path_to_click_-Idealpfad_C4,path_to_click_-Idealpfad_B1,path_to_click_-Idealpfad_B2,path_to_click_-Idealpfad_B3,path_to_click_-Idealpfad_B4
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,1853.643007,1029.099311,...,3.376,4.353,123.268104,198.429072,30.861040,187.960035,8.065651,8.176029,95.762832,15.880454
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,1886.064440,975.492400,...,1.853,2.955,12.315834,13.752972,5.393340,-0.770544,10.636592,42.870294,35.586449,2.352065
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,3004.503424,2836.840990,...,1.436,2.027,673.405958,449.178754,284.121833,78.432564,10.121656,6.462886,317.262201,21.966099
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,2931.175568,1883.701631,...,1.448,3.354,177.230122,19.581664,63.077147,510.267513,97.765431,81.358572,14.490567,149.894947
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,1985.636672,1374.456074,...,1.202,1.452,4.817705,128.282925,45.043016,36.009782,36.030110,6.136803,5.685974,18.927963
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,2936.952732,1636.015808,...,1.106,1.314,285.038131,343.547944,28.867586,41.024516,222.451979,62.321216,208.084527,3.069843
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,2176.615489,1470.069064,...,3.963,5.757,15.540150,250.757211,146.002438,38.378819,33.561392,19.826285,8.278826,255.888121
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,2524.936013,1219.753988,...,1.328,5.171,106.997428,48.804649,2.440313,1.215815,224.495205,80.247424,150.828506,16.616565
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,2749.563567,1065.741990,...,3.127,6.155,4.178623,86.643961,10.170906,32.279254,14.949877,17.062450,41.692778,51.741038
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,2281.663493,1987.613796,...,3.490,3.917,12.766642,-2.352459,63.854387,77.403783,19.189547,40.508934,19.813120,-6.210741
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,1819.565610,1084.454083,...,2.353,4.459,3.954520,22.041748,14.766390,-3.939095,-2.811361,21.596306,22.328522,30.856529
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,2155.066788,962.908791,...,0.902,3.309,-4.809024,29.992637,56.017759,27.844960,6.194216,43.590117,20.684175,14.310675
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,3040.142030,3433.884540,...,1.265,2.871,196.179158,9.571670,265.617033,104.868191,4.314539,3.668789,102.120641,2.113612
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,1798.996408,1166.316327,...,1.392,3.130,-2.946309,131.467428,8.767511,15.852450,1.851928,0.209901,81.648822,-0.638002
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,1303.939517,2160.939399,...,1.720,5.485,7.861917,95.923798,34.490463,6.367638,9.160219,30.680328,4.780126,7.370942
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,3202.784211,1387.548529,...,1.109,3.226,30.868671,7.858790,44.429630,33.042040,197.959494,11.392315,31.345301,8.341376
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,2216.980892,1586.510552,...,1.701,3.893,19.422654,126.151373,14.621105,32.713784,547.327177,1.589176,11.775274,0.477670

In [52]:
columns = [elem for elem in users.columns.tolist() if elem.startswith("path_to_click_-Idealpfad_B")]
users[columns].describe()

,path_to_click_-Idealpfad_B1,path_to_click_-Idealpfad_B2,path_to_click_-Idealpfad_B3,path_to_click_-Idealpfad_B4
count,17.000000,17.000000,17.000000,17.000000
mean,84.780215,28.099872,68.951097,34.879950
std,143.495330,26.554742,85.850741,67.384398
min,-2.811361,0.209901,4.780126,-6.210741
25%,8.065651,6.462886,14.490567,2.352065
50%,14.949877,19.826285,31.345301,14.310675
75%,97.765431,42.870294,95.762832,21.966099
max,547.327177,81.358572,317.262201,255.888121

# Boxplots

In [ ]:
df = px.data.tips()
fig = px.box(df, x="time", y="total_bill")
fig.show()

# Speichern

In [123]:
users.to_csv("./results/analysis.csv", index=False)