In [2]:
import pandas as pd
import os
import math
import plotly.express as px
import plotly.graph_objects as go

In [3]:
users = pd.read_csv("./results/users.csv")

folder_path = './data/tracking_files/'
list_of_filenames = os.listdir(folder_path)

tasks = ["E1", "E2", "E3"]
users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True

# path

In [4]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    path_lengths = []

    for user_nr in users["nr"]:
        
        path_length = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            dx = df_path['x'].iloc[i] - df_path['x'].iloc[i-1]
            dy = df_path['y'].iloc[i] - df_path['y'].iloc[i-1]
            segment_length = math.sqrt(dx**2 + dy**2)
            path_length += segment_length
        path_lengths.append(path_length)

    users["path_" + task] = path_lengths

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_E1,path_E2,path_E3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,622.722904,492.031700,515.905771
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,504.184470,452.645191,438.915928
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,514.016720,488.780575,593.217099
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,467.307732,452.510325,468.088532
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,492.644046,450.760499,467.896643
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,519.098440,524.811476,442.859898
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,757.704066,655.783794,575.245990
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,451.605138,464.128626,498.273308
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,890.121131,479.531061,713.576041
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,755.765691,462.734516,500.180918
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,523.808668,525.000092,490.811323
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,531.727165,440.324626,493.590238
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,583.854219,644.263257,699.453714
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,471.314932,434.232297,453.121944
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,725.349891,612.039960,543.856419
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,507.261573,563.209412,478.474402
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,500.209287,445.197928,522.551026

# time

In [5]:
for task in tasks:
    
    task_times = []

    for user in users["nr"]:
        df = pd.read_csv("data/tracking_files/" + str(user) + "_" + task + ".csv")
        task_times.append(df.iloc[-1]["ms"] / 1000)

    users["time_" + task] = task_times

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_E1,path_E2,path_E3,time_E1,time_E2,time_E3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,622.722904,492.031700,515.905771,3.809,1.697,1.400
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,504.184470,452.645191,438.915928,2.204,2.305,1.369
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,514.016720,488.780575,593.217099,1.070,1.295,1.031
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,467.307732,452.510325,468.088532,2.102,2.759,1.479
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,492.644046,450.760499,467.896643,1.460,1.441,1.658
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,519.098440,524.811476,442.859898,1.583,1.720,1.388
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,757.704066,655.783794,575.245990,4.874,7.537,5.068
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,451.605138,464.128626,498.273308,2.041,1.933,1.995
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,890.121131,479.531061,713.576041,2.424,2.481,1.911
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,755.765691,462.734516,500.180918,8.075,3.298,2.869
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,523.808668,525.000092,490.811323,4.433,2.600,3.917
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,531.727165,440.324626,493.590238,2.349,3.089,2.261
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,583.854219,644.263257,699.453714,1.463,1.833,3.369
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,471.314932,434.232297,453.121944,1.128,1.166,1.955
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,725.349891,612.039960,543.856419,2.805,4.350,1.673
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,507.261573,563.209412,478.474402,1.826,2.065,1.748
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,500.209287,445.197928,522.551026,3.396,1.665,1.880

# Kontrolle

nicht nötig, da man ohne Klick auf "Ok" gar nicht weiter kommt.

# Strecke pro Sekunde

In [6]:
for task in tasks:
    users["v_" + task] = users["path_" + task] / users["time_" + task] 

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_E1,path_E2,path_E3,time_E1,time_E2,time_E3,v_E1,v_E2,v_E3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,622.722904,492.031700,515.905771,3.809,1.697,1.400,163.487242,289.942074,368.504122
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,504.184470,452.645191,438.915928,2.204,2.305,1.369,228.758834,196.375354,320.610612
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,514.016720,488.780575,593.217099,1.070,1.295,1.031,480.389458,377.436737,575.380309
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,467.307732,452.510325,468.088532,2.102,2.759,1.479,222.315762,164.012441,316.489879
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,492.644046,450.760499,467.896643,1.460,1.441,1.658,337.427429,312.810894,282.205454
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,519.098440,524.811476,442.859898,1.583,1.720,1.388,327.920682,305.122951,319.063327
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,757.704066,655.783794,575.245990,4.874,7.537,5.068,155.458364,87.008597,113.505523
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,451.605138,464.128626,498.273308,2.041,1.933,1.995,221.266604,240.107929,249.761057
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,890.121131,479.531061,713.576041,2.424,2.481,1.911,367.211688,193.281363,373.404522
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,755.765691,462.734516,500.180918,8.075,3.298,2.869,93.593274,140.307616,174.339811
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,523.808668,525.000092,490.811323,4.433,2.600,3.917,118.161215,201.923112,125.302865
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,531.727165,440.324626,493.590238,2.349,3.089,2.261,226.363204,142.546010,218.306165
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,583.854219,644.263257,699.453714,1.463,1.833,3.369,399.080122,351.480228,207.614638
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,471.314932,434.232297,453.121944,1.128,1.166,1.955,417.832386,372.411919,231.775930
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,725.349891,612.039960,543.856419,2.805,4.350,1.673,258.591762,140.698841,325.078553
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,507.261573,563.209412,478.474402,1.826,2.065,1.748,277.799328,272.740635,273.726774
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,500.209287,445.197928,522.551026,3.396,1.665,1.880,147.293665,267.386143,277.952673

# Describe

In [7]:
users.describe()

,nr,age,sorting_option,num_of_files,path_E1,path_E2,path_E3,time_E1,time_E2,time_E3,v_E1,v_E2,v_E3
count,17.000000,17.000000,17.000000,17.0,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,9.000000,36.764706,1.764706,23.0,577.570357,505.175608,523.295247,2.767176,2.543176,2.174765,261.350060,238.564285,279.589542
std,5.049752,15.254218,0.831370,0.0,127.744378,72.245242,81.025504,1.762695,1.523164,1.058318,112.082527,88.982376,107.672136
min,1.000000,19.000000,1.000000,23.0,451.605138,434.232297,438.915928,1.070000,1.166000,1.031000,93.593274,87.008597,113.505523
25%,5.000000,25.000000,1.000000,23.0,500.209287,452.510325,468.088532,1.583000,1.697000,1.479000,163.487242,164.012441,218.306165
50%,9.000000,29.000000,2.000000,23.0,519.098440,479.531061,498.273308,2.204000,2.065000,1.880000,228.758834,240.107929,277.952673
75%,13.000000,54.000000,2.000000,23.0,622.722904,525.000092,543.856419,3.396000,2.759000,2.261000,337.427429,305.122951,320.610612
max,17.000000,61.000000,3.000000,23.0,890.121131,655.783794,713.576041,8.075000,7.537000,5.068000,480.389458,377.436737,575.380309

# Zeit in Ruhe

In [11]:
for task in tasks:
    
    task_dict = {}

    for file in list_of_filenames:
        if file.split("_")[1] == task + ".csv":
            df = pd.read_csv("data/tracking_files/" + file)
            task_dict[file.split("_")[0]] = df

    times_ruhe = []

    for user_nr in users["nr"]:
        
        time_ruhe = 0
        df_path = task_dict[str(user_nr)]

        for i in range(1, len(df_path)):
            dms = df_path['ms'].iloc[i] - df_path['ms'].iloc[i-1]
            if dms > 500:
                time_ruhe += dms
        times_ruhe.append(time_ruhe / 1000)

    users["time_ruhe_" + task] = times_ruhe
    users["time_ruhe_pr_" + task] = users["time_ruhe_" + task] / users["time_" + task] * 100

users

,nr,uuid,age,gender,device,sorting_option,num_of_files,coords_match,path_E1,path_E2,...,time_E3,v_E1,v_E2,v_E3,time_ruhe_E1,time_ruhe_pr_E1,time_ruhe_E2,time_ruhe_pr_E2,time_ruhe_E3,time_ruhe_pr_E3
0,1,649bf93e99881a2b49291e23,61,male,mouse,3,23,True,622.722904,492.031700,...,1.400,163.487242,289.942074,368.504122,2.261,59.359412,0.514,30.288745,0.000,0.000000
1,2,649afe9b8c617b636a488066,41,male,mouse,2,23,True,504.184470,452.645191,...,1.369,228.758834,196.375354,320.610612,0.799,36.252269,1.824,79.132321,0.000,0.000000
2,3,649ad0398c611bb012843f4d,25,male,mouse,2,23,True,514.016720,488.780575,...,1.031,480.389458,377.436737,575.380309,0.000,0.000000,0.000,0.000000,0.000,0.000000
3,4,649af42c8c611c4708e4e18d,25,male,touchpad,2,23,True,467.307732,452.510325,...,1.479,222.315762,164.012441,316.489879,0.643,30.589914,1.570,56.904676,0.000,0.000000
4,5,649b2b1e8c61127922e1a7fa,25,male,mouse,1,23,True,492.644046,450.760499,...,1.658,337.427429,312.810894,282.205454,0.000,0.000000,0.000,0.000000,0.000,0.000000
5,6,64a1b2e38c611f9c485e8b29,40,female,touchpad,1,23,True,519.098440,524.811476,...,1.388,327.920682,305.122951,319.063327,0.000,0.000000,0.000,0.000000,0.000,0.000000
6,7,649b269e8c617a4301bc7247,55,female,mouse,1,23,True,757.704066,655.783794,...,5.068,155.458364,87.008597,113.505523,3.207,65.798112,6.082,80.695237,3.466,68.389897
7,8,64a26a678c6147cbab24d968,19,female,touchpad,1,23,True,451.605138,464.128626,...,1.995,221.266604,240.107929,249.761057,1.248,61.146497,1.269,65.649250,0.680,34.085213
8,9,649be8ba8c619f5efb2614e0,59,female,mouse,2,23,True,890.121131,479.531061,...,1.911,367.211688,193.281363,373.404522,0.000,0.000000,1.096,44.175736,0.000,0.000000
9,10,64a040d18c6121bf2c739076,29,female,touchpad,3,23,True,755.765691,462.734516,...,2.869,93.593274,140.307616,174.339811,6.248,77.374613,2.338,70.891449,1.117,38.933426
10,11,649aba058c612604f08fde63,23,female,touchpad,3,23,True,523.808668,525.000092,...,3.917,118.161215,201.923112,125.302865,2.160,48.725468,0.675,25.961538,1.306,33.341843
11,12,649b38738c611b846db1a58d,25,female,mouse,1,23,True,531.727165,440.324626,...,2.261,226.363204,142.546010,218.306165,0.993,42.273308,2.032,65.781806,1.032,45.643521
12,13,64995bac8c61d60b08d58991,26,female,mouse,1,23,True,583.854219,644.263257,...,3.369,399.080122,351.480228,207.614638,0.000,0.000000,0.000,0.000000,1.177,34.936183
13,14,649c8b1d8c61291698048377,25,female,touchpad,1,23,True,471.314932,434.232297,...,1.955,417.832386,372.411919,231.775930,0.000,0.000000,0.000,0.000000,0.913,46.700767
14,15,649b48cd8c61c6ca0bbae44b,32,female,mouse,2,23,True,725.349891,612.039960,...,1.673,258.591762,140.698841,325.078553,0.542,19.322638,1.664,38.252874,0.000,0.000000
15,16,649b30938c6117fb06cfde92,54,male,mouse,1,23,True,507.261573,563.209412,...,1.748,277.799328,272.740635,273.726774,0.751,41.128149,0.700,33.898305,0.678,38.787185
16,17,649bdcfe8c6121e7a6d49d14,61,male,mouse,3,23,True,500.209287,445.197928,...,1.880,147.293665,267.386143,277.952673,2.061,60.689046,0.558,33.513514,0.627,33.351064

In [13]:
users[["time_ruhe_E1", "time_ruhe_E2", "time_ruhe_E3", "time_ruhe_pr_E1", "time_ruhe_pr_E2", "time_ruhe_pr_E3"]].describe()

,time_ruhe_E1,time_ruhe_E2,time_ruhe_E3,time_ruhe_pr_E1,time_ruhe_pr_E2,time_ruhe_pr_E3
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,1.230176,1.195412,0.646824,31.921143,36.773262,22.009947
std,1.621617,1.482952,0.882225,27.856294,29.542613,22.820764
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.751000,0.700000,0.627000,36.252269,33.898305,33.341843
75%,2.061000,1.664000,1.032000,59.359412,65.649250,38.787185
max,6.248000,6.082000,3.466000,77.374613,80.695237,68.389897

# Speichern

In [10]:
users.to_csv("./results/analysis_E.csv", index=False)